name: "Continuous Integration"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-test:
    name: "CI Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: "v1.48.0"

      - name: Test
        run: go test -v ./...
